services:
  app:
    build: .
    ports:
      - "3000:3000"       
    environment:
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=${NODE_ENV} 
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5433"        
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:           
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
